


server:
  port: 8092



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/players_db
    username: root
    password: jaiganeshji
    driver-class-name: com.mysql.cj.jdbc.Driver




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: org.hibernate.dialect.MySQL8Dialect

